/**
 * Created by siri on 2017-06-12.
 */
export const AUTH_USER='AUTH_USER';
export const UNAUTH_USER='UNAUTH_USER';
export const AUTH_ERROR='AUTH_ERROR';
export const FETCH_MESSAGE='FETCH_MESSAGE';

export const BIlLING_SUCCESS='BIlLING_SUCCESS';
export const BIlLING_INIT='BIlLING_INIT';


export const BOOK_LIST = "BOOK_LIST";
export const BOOK_LIST_SUCCESS = "BOOK_LIST_SUCCESS";
export const BOOK_LIST_FAILURE = "BOOK_LIST_FAILURE";

export const BOOK_POST='BOOK_POST';
export const BOOK_POST_SUCCESS='BOOK_POST_SUCCESS';
export const BOOK_POST_FAILURE='BOOK_POST_FAILURE';

export const BOOK_DELETE_SUCCESS="BOOK_DELETE_SUCCESS";
export const BOOK_DELETE_FAILURE="BOOK_DELETE_FAILURE";

export const BOOK_EDIT_SUCCESS = "BOOK_EDIT_SUCCESS";
export const BOOK_EDIT_FAILURE = "BOOK_EDIT_FAILURE";
export const LOAD='LOAD';

/* INVOICE  */
export const INVOICE_LIST_SUCCESS = "INVOICE_LIST_SUCCESS";
export const INVOICE_LIST_FAILURE = "INVOICE_LIST_FAILURE";
export const INVOICE_LIST_INIT="INVOICE_LIST_INIT";



